SSAFY-FarAway/faraway-client

- src/App.vue
- src/assets/css/kakao_map.css
- src/components/plan/PlanKakaoMap.vue
- src/components/plan/PlanPagination.vue
- src/utils/api/kakao_config.js
- src/views/plan/PlanDetail.vue
- src/views/plan/PlanList.vue
- # FAR-95/feat : 여행계획 상세조회 지도
- # FAR-96/feat : 여행계획 상세조회
- # FAR-97/feat : 지도 띄우기
<br>
- 여행계획 전체조회
- 여행계획 상세조회
<br>
<br>
> FAR-95/feat : 여행계획 조회

- src/assets/css/style.css
- src/components/common/TheFooter.vue
- src/components/plan/PlanKakaoMap.vue
- src/router/index.js
- src/store/modules/memberStore.js
- src/views/plan/PlanDetail.vue
- src/views/plan/PlanList.vue
- src/views/plan/PlanWrite.vue
🔍 Commit
- refactor : UI 변경
🔧 DONE
여행 계획 상세조회
여행 계획 쓰기 View
🔧 TODO
📝 리뷰할 때 참고할 점
> Far 95/feat

- src/App.vue
- src/assets/css/kakao_map.css
- src/assets/css/style.css
- src/components/common/TheFooter.vue
- src/components/plan/PlanKakaoMap.vue
- src/components/plan/PlanPagination.vue
- src/components/plan/PlanTableRow.vue
- src/router/index.js
- src/store/modules/memberStore.js
- src/utils/api/kakao_config.js
- src/views/plan/PlanDetail.vue
- src/views/plan/PlanList.vue
- src/views/plan/PlanWrite.vue
🔍 Commit
🔧 DONE
여행 계획 전체조회
여행 계획 상세조회
🔧 TODO
📝 리뷰할 때 참고할 점
> FAR-4/plan : 여행계획 조회 구현

- .gitignore
- src/components/post/PostPagination.vue
- src/components/post/PostTableRow.vue
- src/main.js
- src/router/index.js
- src/utils/filters.js
- src/views/post/PostDetail.vue
- src/views/post/PostList.vue
- src/views/post/PostModify.vue
- src/views/post/PostWrite.vue
- #
<br>
- 게시글 전체조회 화면
- 게시글 상세조회 화면
- 게시글 수정화면
- 게시글 삭제 요청 버튼
- 게시글 관련 초안 화면
<br>
- 코드리뷰
- 리팩토링
- 버그 수정
<br>
컨벤션, 구조 등 제대로 리팩토링해야함
> Far-1/post: 게시글 구현

- src/components/common/CommentItem.vue
- src/views/post/PostDetail.vue
- src/views/post/PostList.vue
- src/views/post/PostWrite.vue
- #
<br>
- 리팩토링 수행
<br>
- 작업 못한 내용 작성
<br>
> Far-1/post: 리팩토링

- src/views/hotplace/HotPlaceList.vue
- #
<br>
- 리팩토링
<br>
- 작업 못한 내용 작성
<br>
> Far-5/hotplace

- package-lock.json
- package.json
- src/components/attraction/AttractionKakaoMap.vue
- src/components/attraction/AttractionSearchSidebar.vue
- src/components/common/TheNavbar.vue
- src/components/plan/PlanKakaoMap.vue
- src/main.js
- src/store/index.js
- src/store/modules/attractionStore.js
- src/store/modules/memberStore.js
- src/utils/api/http.js
- src/views/member/MemberLogin.vue
- src/views/plan/PlanWrite.vue
- #
<br>
-  accesstoken, refreshtoken 세션에서 관리
<br>
- refreshtoken 재발급
<br>
> Far 118/feat

- src/components/common/comment/CommentForm.vue
- src/components/common/comment/CommentRow.vue
- src/components/common/navigation/TheNavbar.vue
- src/components/common/page/tableRowData.vue
- src/router/index.js
- src/views/hotplace/HotPlaceDetail.vue
- src/views/post/PostDetail.vue
- src/views/post/PostList.vue
- src/views/post/PostWrite.vue
- #
<br>
- 게시판 디자인 개선 
- 불필요한 코드 제거
- 공통 부분 컴포넌트화
<br>
- 작업 못한 내용 작성
<br>
> Far 133/feat

- src/utils/api/http.js
- #
<br>
- http 헤더 추가
<br>
- 작업 못한 내용 작성
<br>
> fix : authorization 추가

- src/utils/api/http.js
- src/views/home/TheIndex.vue
- src/views/member/MemberLogin.vue
- #
<br>
- 로그인 인증 버그 수정
<br>
- 작업 못한 내용 작성
<br>
> fix : 버그 수정

- package-lock.json
- src/views/hotplace/HotPlaceDetail.vue
- src/views/hotplace/HotPlaceWrite.vue
<br>
- hot-place 상세조회 화면 구현
<br>
- 작업 못한 내용 작성
<br>
> FAR-157/feat:hot-place 상세조회 화면 구현

- src/router/index.js
- src/store/modules/memberStore.js
- #
<br>
- 작업내용 작성
<br>
- 작업 못한 내용 작성
<br>
> Far-134/refactor: 전역가드구현

- src/router/index.js
- src/views/post/PostDetail.vue
- src/views/post/PostModify.vue
- #
<br>
- 작업내용 작성
<br>
- 작업 못한 내용 작성
<br>
> FAR-133/refactor: 게시판 개선

- src/components/attraction/AttractionSearchResultItem.vue
- src/components/attraction/AttractionSearchResultTotopItem.vue
- src/components/attraction/AttractionSearchSidebar.vue
- src/components/plan/PlanAddCard.vue
- src/components/plan/PlanDetailKakaoMap.vue
- src/components/plan/PlanWriteKakaoMap.vue
- src/router/index.js
- src/utils/common.js
- src/views/plan/PlanDetail.vue
- src/views/plan/PlanModify.vue
- src/views/plan/PlanWrite.vue
- #
<br>
- 여행계획 작성, 수정, 삭제
<br>
- 지도 버그 수정 (조회시 지도 여러개 렌더링됨)
- 추가한 경로 marker와 line 표시하기
<br>
> FAR-107/feat:여행계획 작성, 수정, 삭제

- src/views/member/MemberRegister.vue
- #
<br>
-[Client] 회원가입 리팩토링
아이디 비밀번호 체크
주소 API 사용
전체 항목 입력 검사
<br>
- 작업 못한 내용 작성
<br>
> FAR-169/refactor:회원가입 리팩토링

- src/components/plan/PlanDetailKakaoMap.vue
- src/utils/common.js
- src/views/plan/PlanDetail.vue
- src/views/post/PostDetail.vue
- src/views/post/PostList.vue
- #
<br>
- plan 지도 렌더링
- 토스트 메시지 출력시간 수정
- 게시판 헤더 출력 버그 수정
<br>
- 작업 못한 내용 작성
<br>
> FAR-107/feat

- src/assets/css/style.css
- src/components/hotplace/FeedItem.vue
- src/router/index.js
- src/views/hotplace/HotPlaceDetail.vue
- src/views/hotplace/HotPlaceList.vue
- src/views/hotplace/HotPlaceModify.vue
- src/views/hotplace/HotPlaceWrite.vue
- src/views/plan/PlanDetail.vue
- src/views/post/PostDetail.vue
- src/views/post/PostModify.vue
- #
<br>
- hotplace View 개선 (전체조회 뷰 - 인스타 형식, 작성 뷰 )
- 
<br>
- 작업 못한 내용 작성
<br>
> FAR-178/feat

- src/components/common/navigation/TheNavbar.vue
- src/router/index.js
- src/views/member/MemberFind.vue
- src/views/member/MemberMyPage.vue
- src/views/member/MemberRegister.vue
- src/views/member/MemberUpdatePwd.vue
- 비밀번호 변경 화면 구현
- 아이디 비밀번호 찾기 API 연결
- 마이페이지 비밀번호 입력 모달창
- 마이페이지 주소 수정 Daum API 추가
<br>
- 회원 탈퇴 미구현
<br>
> Far 2/member

- src/views/hotplace/HotPlaceList.vue
- #
<br>
- FAR-178/feat 핫플레이스 무한스크롤 구현
- totop버튼 구현
<br>
- 작업 못한 내용 작성
<br>
> FAR-178/feat 핫플레이스

- src/components/common/navigation/TheNavbar.vue
- src/views/member/MemberMyPage.vue
- 회원탈퇴 화면 구현
- 모달 창 수정 
- 비밀번호 변경 접근 방식 변경
<br>
- 작업 못한 내용 작성
<br>
> FAR-180/feat:회원 탈퇴 구현

- .gitignore
- package-lock.json
- public/index.html
- src/components/home/TagSearchBar.vue
- src/utils/api/http.js
- src/views/home/TheIndex.vue
- #
<br>
- 작업내용 작성
<br>
- 작업 못한 내용 작성
<br>
> Far 182/feat
